=== yukinago/famille-works/JForexStrategy/build/tmp/expandedArchives/msg-0.0.4.jar_26876983dr3metca3ffo8b6khc/schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="messages">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="message" minOccurs="1" maxOccurs="unbounded" />
				<xs:element ref="enum" minOccurs="0" maxOccurs="unbounded" />
			</xs:choice>
			<xs:attribute name="autoExtends" type="xs:string" />
			<xs:attribute name="package" type="xs:string" use="required" />
		</xs:complexType>
		<xs:unique name="messageName">
			<xs:selector xpath="message" />
			<xs:field xpath="@class" />
		</xs:unique>
		<xs:unique name="enumName">
			<xs:selector xpath="enum" />
			<xs:field xpath="@class" />
		</xs:unique>
	</xs:element>

	<xs:element name="enum">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="class" type="xs:string" use="required" />
					<xs:attribute name="values" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="constructor">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="fields" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="message">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element type="xs:string" minOccurs="0" name="comments" />
				<xs:element ref="constructor" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="fields" minOccurs="1" maxOccurs="1" />
				<xs:element ref="method" minOccurs="0" maxOccurs="unbounded" />
			</xs:choice>
			<xs:attribute name="class" type="xs:string" use="optional" />
			<xs:attribute name="interface" type="xs:string" use="optional" />
			<xs:attribute name="extends" type="xs:string" />
			<xs:attribute name="implements" type="xs:string" />
		</xs:complexType>
		<xs:unique name="fieldName">
			<xs:selector xpath="fields/*" />
			<xs:field xpath="@name" />
		</xs:unique>
	</xs:element>
	
	<xs:element name="method">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="name" type="xs:string" />
					<xs:attribute name="returnType" type="xs:string" />
					<xs:attribute name="argNames" type="xs:string" />
					<xs:attribute name="argTypes" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="fields">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="field" />
				<xs:element ref="set" />
				<xs:element ref="list" />
				<xs:element ref="map" />
				<xs:element ref="array" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="commonField">
		<xs:sequence>	
			<xs:element type="xs:string" name="comments" minOccurs="0" maxOccurs="1"></xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="default" type="xs:string" />
		<xs:attribute name="transient" type="xs:boolean" />

	</xs:complexType>

	<xs:element name="field">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="commonField">
					<xs:attribute name="constant" type="xs:boolean" use="optional"/>
					<xs:attribute name="type" type="xs:string" use="required" />
					<xs:attribute name="generateToString" type="xs:boolean" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="set">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="commonField">
					<xs:attribute name="elementClass" type="xs:string"
						use="required" />
						<xs:attribute name="generateToString" type="xs:boolean" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="list">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="commonField">
					<xs:attribute name="elementClass" type="xs:string"
						use="required" />
						<xs:attribute name="generateToString" type="xs:boolean" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="array">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="commonField">
					<xs:attribute name="elementClass" type="xs:string"
						use="required" />
					<xs:attribute name="generateToString" type="xs:boolean" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="map">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="commonField">
					<xs:attribute name="keyClass" type="xs:string" use="required" />
					<xs:attribute name="valueClass" type="xs:string" use="required" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== yukinago/famille-works/JForexStrategy/build/tmp/expandedArchives/msg-0.0.4.jar_26876983dr3metca3ffo8b6khc/Types.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd" package="com.dukascopy.dds3.transport.msg.types">

	<enum class="OrderSide" values="BUY, SELL" />
	<enum class="OrderState" values="CREATED, PENDING, EXECUTING, FILLED, REJECTED, CANCELLED, ERROR" />
	<enum class="OfferSide" values="ASK, BID" />
	<enum class="TimeInForce" values="IOC, GTC, FOK" />
	<enum class="TradabilityState" values="TRADING_ALLOWED, TRADING_TEMPORARY_BLOCKED, TRADING_RESTRICTED" />
	<enum class="RejectReason" values="INVALID_ORDER, SERVICE_OFFILNE, EXECUTION_RESTRICTED, STALE_PRICE, REJECTED_BY_COUNTERPARTY" />
    <enum class="SqlAction" values="EXECUTE, SELECT" />
    <enum class="AccountState" values="OK, MARGIN_CLOSING, MARGIN_CALL, OK_NO_MARGIN_CALL, DISABLED, BLOCKED" />
    <enum class="OrderDirection" values="OPEN, CLOSE" />
    <enum class="StopDirection" values="GREATER_BID,GREATER_ASK,LESS_BID,LESS_ASK"/>
    <enum class="CustRejectReason" values="MARGIN, LIQUIDITY, ERROR, INVALID_ORDER, CONNECTION" />
    <enum class="PositionSide" values="LONG, SHORT" />
    <enum class="PositionStatus" values="OPEN, CLOSE" />
    <enum class="NotificationMessageCode" values="SYSTEM_UNAVAILABLE, ACCOUNT_BLOCKED, ACCOUNT_BLOCKED_CLOSED, MERGE_IN_PROGRESS, NO_ORDER_FOUND, VALIDATION_ERROR, UPDATE_ORDER_NOT_FOUND, ORDER_ALREADY_FILLED, ORDER_IN_EXEC_STATE, ORDER_IN_ERROR_STATE, ORDER_FILLED, ORDER_FILLED_PARTIALLY, REJECTED_COUNTERPARTY, REJECT_AND_RESUBMIT, MAX_SUBMIT_COUNT_REACHED, MC_NOT_RESUBMIT, REJECT_INVALID_ORDER, REJECT_NO_MARGIN, FAILED_CANCEL_OFFER, FAILED_EDIT_OFFER, REJECTED_MIN_OPEN_AMOUNT, AMOUNT_GREATER_REMAINING, UNSUFFICIENT_MARGIN, CANCELING_OFFER_MC, EQUITY_LIMIT_REACHED, OFFER_CANCELED, OFFER_CANCELED_FILLED, OFFER_CANCELED_LEVERAGE, ORDER_CANCELED, SL_TP_DISABLED_NONHADGE, AMOUNT_EMPTY_OR_ZERO, PRICE_STOP_INVALID, STEP_LESS_3PIP, PRICE_CLIENT_EMPTY, AMOUNT_TO_LARGE, INSTRUMENT_EMPTY, ORDER_DIRECTION_EMPTY, ORDER_STATE_EMPTY, ORDER_SIDE_EMPTY, INVALID_ORDER, GROUP_MISSED, ORDER_NOT_FOUND, ACCOUNT_DISABLED, MAS_CLOSE_FAIL_BAD_ORDER, UNSUFF_MARGIN_ON_CLOSE, POSITION_MERGED_CLOSED, POSITION_MERGED_TO, POSITION_MERGE_FAILED, ACCOUNT_SETTING_SAVE_FAIL, STRING_MESSAGE, OCO_GROUPED, OCO_UNGROUPED, MC_MARGIN_CUT_WEEKEND, MC_MARGIN_CUT, ACCOUNT_STATUS_DISABLED, POSITION_LIMIT_REACHED, NEWS_REQUEST_LIMIT_EXCEEDED, ORDER_ACCEPTED, MULTIPLE_SIM_ORDERED, ACCOUNT_LOCKED, NO_MARGIN_LEVEL, MERGE_DENIED, CONDITION_CHANGED, DEACT_CLIENT_DLL_ST, DEACT_CLIENT_DLL_MC, DEACT_CLIENT_LL_ST, DEACT_CLIENT_LL_MC, DEACT_CLIENT_OTHER, ALREADY_PROCESSED, POSITION_LIMIT, SYSTEM_ERROR, ORDER_LOCKED, TRALING_UPDATE, CONTEST_OVER, WITHDRAWAL_DIONE, MC_CLOSING" />
    <enum class="NotificationLevel" values="INFO, WARNING, ALERT, ERROR, INFOCLIENT, NOTIFCLIENT"/>
	<enum class="TaskStatus" values="STARTED, IN_PROGRESS, FINISHED" />
	<enum class="FundRatioChangeStatus" values="OK, ERROR" />
	<enum class="DataFormat" values="CSV, CHART" />
</messages>

=== yukinago/famille-works/JForexStrategy/build/tmp/expandedArchives/msg-0.0.4.jar_26876983dr3metca3ffo8b6khc/ddsapi.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schema.xsd" package="com.dukascopy.dds3.transport.msg.ddsApi"
	autoExtends="com.dukascopy.dds4.transport.msg.system.ProtocolMessage">
	<message class="InitRequestMessage">
		<fields>
			<field name="sendGroups" type="boolean" default="true" />
			<set name="userIdList" elementClass="String" />
		</fields>
	</message>
	<message class="QuitRequestMessage">
		<fields />
	</message>
	<message class="QuitResponseMessage">
		<fields />
	</message>
	<message class="ApiOnlineMessage">
		<fields />
	</message>
	<message class="CustodianOnlineMessage">
		<constructor fields="online" />
		<fields>
			<field name="online" type="boolean" />
		</fields>
	</message>

</messages>

=== yukinago/famille-works/JForexStrategy/build/tmp/expandedArchives/msg-0.0.4.jar_26876983dr3metca3ffo8b6khc/ras.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd" package="com.dukascopy.dds3.transport.msg.ras" autoExtends="com.dukascopy.dds4.transport.msg.system.ProtocolMessage">

	<message class="DynaSqlMessage">
	    <constructor fields="action"></constructor>
		<fields>
			<field name="sync" type="boolean" default="false" />
			<field name="action" type="com.dukascopy.dds3.transport.msg.types.SqlAction"/>
			<field name="query" type="String" />
			<list name="requestParams" elementClass="RequestParam" />
            <list name="returnData" elementClass="java.util.Map"/>
		</fields>
	</message>

	<message class="RequestParam">
	   <constructor fields="index, value, type"></constructor>
		<fields>
			<field name="index" type="int" />
			<field name="value" type="java.io.Serializable" />
			<field name="type" type="int">
				<comments>SQL data type. See java.sql.Types</comments>
			</field>
		</fields>
	</message>

    <message class="AdminMessage">
        <constructor fields="name"></constructor>
        <fields>
            <field name="name" type="String" />
            <field name="reloadUserId" type="String" />
        </fields>
    </message>

    <message class="IdRezMessage">
        <constructor fields="sequence,idCount"></constructor>
        <constructor fields=""></constructor>
        <fields>
            <field name="sequence" type="String" />
            <field name="idCount" type="Long" />
            <list name="ids" elementClass="Long"/>
        </fields>
    </message>

    <message class="OrderResponse">
        <constructor fields="action"/>
        <fields>
            <field name="action" type="String" />
            <list name="listResponse" elementClass="com.dukascopy.dds4.transport.msg.system.ProtocolMessage"/>
        </fields>
    </message>

    <message class="OrderRequest">
        <constructor fields="action"/>
        <fields>
            <field name="action" type="String" />
            <field name="message" type="com.dukascopy.dds4.transport.msg.system.ProtocolMessage"/>
            <map name="properties" keyClass="String" valueClass="String"/>
        </fields>
    </message>

    <message class="DbWriteMessage">
        <constructor fields="queueName, queueId, action, message"></constructor>
        <fields>
            <field name="queueName" type="String" />
            <field name="queueId" type="String" />
            <field name="action" type="String" />
            <field name="message" type="com.dukascopy.dds4.transport.msg.system.ProtocolMessage"/>
        </fields>
    </message>

    <message class="DbProcedurePost">
        <constructor fields="sql"></constructor>
        <fields>
            <field name="sql" type="String" />
            <map name="parameters" keyClass="String" valueClass="String"/>
        </fields>
    </message>

</messages>

=== yukinago/famille-works/JForexStrategy/build/tmp/expandedArchives/msg-0.0.4.jar_26876983dr3metca3ffo8b6khc/monitor.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schema.xsd"
	package="com.dukascopy.dds3.transport.msg.monitor" autoExtends="com.dukascopy.dds4.transport.msg.system.ProtocolMessage">
	
	<message class="TaskProgressMessage">
		<constructor fields="taskId" />
		<fields>
			<field name="taskId" type="String" />
			<field name="maxDuration" type="int" />
			<field name="progress" type="int" />
			<field name="status" type="com.dukascopy.dds3.transport.msg.types.TaskStatus" />
			<field name="text" type="String" />
		</fields>
	</message>

</messages>

=== yukinago/famille-works/JForexStrategy/build/tmp/expandedArchives/msg-0.0.4.jar_26876983dr3metca3ffo8b6khc/executor.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd" package="com.dukascopy.dds3.transport.msg.executor" autoExtends="com.dukascopy.dds4.transport.msg.system.ProtocolMessage">

	<message class="ExecutorOrderMessage">
		<fields>
			<field name="orderId" type="String" />
			<field name="rootOrderId" type="String" />
			<field name="timeInForce" type="com.dukascopy.dds3.transport.msg.types.TimeInForce" />
			<field name="side" type="com.dukascopy.dds3.transport.msg.types.OrderSide" />
			<field name="instrument" type="String" />
			<field name="amount" type="BigDecimal" />
			<field name="price" type="BigDecimal" />
			<field name="managerId" type="String" />
			<field name="partyId" type="String" />
			<field name="executor" type="String" />
		</fields>
	</message>

	<message class="ExecutorTradeMessage">
		<fields>
			<field name="tradeId" type="String" />
			<field name="orderId" type="String" />
			<field name="rootOrderId" type="String" />
			<field name="executorId" type="String" />
			<field name="brokerId" type="String" />
			<field name="primeBrokerId" type="String" />
			<field name="counterparty" type="String" />
			<field name="side" type="com.dukascopy.dds3.transport.msg.types.OrderSide" />
			<field name="instrument" type="String" />
			<field name="executionPrice" type="BigDecimal" />
			<field name="executedAmount" type="BigDecimal" />
			<field name="secondaryAmount" type="BigDecimal" />
			<field name="valueDate" type="java.util.Date" />
			<field name="tradeDate" type="java.util.Date" />
			<field name="transactionTime" type="java.util.Date" />
			<field name="managerId" type="String" />
			<field name="dropCopy" type="boolean" />
		</fields>
	</message>

	<message class="ExecutionResultMessage">
		<fields>
			<field name="orderId" type="String" />
			<field name="orderState" type="com.dukascopy.dds3.transport.msg.types.OrderState" />
			<field name="rejectReason" type="com.dukascopy.dds3.transport.msg.types.RejectReason" />
			<field name="notes" type="String" />
		</fields>
	</message>

	<message class="ExecutorOnlineMessage">
		<constructor fields="online" />
		<fields>
			<field name="online" type="boolean" />
		</fields>
	</message>

	<message class="ExecutorInfoMessage">
		<constructor fields="executorId, status" />
		<fields>
			<field name="executorId" type="String" />
			<field name="status" type="com.dukascopy.dds4.transport.msg.types.ServiceStatus" />
			<field name="version" type="String" />
			<map name="instrumentStates" keyClass="String" valueClass="com.dukascopy.dds3.transport.msg.types.TradabilityState">
			</map>
		</fields>
	</message>

	<message class="LockExecutorRequest">
		<fields>
			<field name="reason" type="String" />
		</fields>
	</message>


</messages>

=== yukinago/famille-works/JForexStrategy/build/tmp/expandedArchives/msg-0.0.4.jar_26876983dr3metca3ffo8b6khc/acc.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="schema.xsd"
          package="com.dukascopy.dds3.transport.msg.acc"
          autoExtends="com.dukascopy.dds4.transport.msg.system.ProtocolMessage">

    <message class="MoneyMessage" extends="com.dukascopy.dds4.transport.msg.system.ProtocolObject">
        <fields>
            <field name="currency" type="String"/>
            <field name="value" type="BigDecimal"/>
        </fields>
    </message>
    <message class="SetlQuote">
    <constructor fields="bid,ask,price,instrument" />
    <fields>
        <field name="bid" type="BigDecimal"/>
        <field name="ask" type="BigDecimal"/>
        <field name="price" type="BigDecimal"/>
        <field name="commMulti" type="BigDecimal"/>
        <field name="instrument" type="String"/>
    </fields>
    </message>

    <message class="ClientInfoMessage">
        <fields>
            <field name="clientId" type="String"/>
            <field name="ratio" type="BigDecimal"/>
            <field name="lossLimit" type="BigDecimal"/>
            <field name="dayLossLimit" type="BigDecimal"/>
            <field name="lossLimitCur" type="String"/>
            <field name="lossLimitType" type="Integer"/>
            <field name="lossLimitAmnt" type="String"/>
            <field name="state" type="com.dukascopy.dds3.transport.msg.types.AccountState"/>
            <list name="closedPL" elementClass="MoneyMessage"/>
            <field name="balanceSystemUsd" type="BigDecimal"/>
            <field name="balanceMultiplicator" type="BigDecimal"/>

            <field name="takeProfit" type="BigDecimal"/>
            <field name="minLossLimit" type="BigDecimal"/>
            <map name="instrQuote" keyClass="String" valueClass="SetlQuote"/>


        </fields>
    </message>

    <message class="FeedCommission">
        <fields>
            <field name="mapId" type="Integer"/>
            <field name="feedComAskPip" type="BigDecimal"/>
            <field name="feedComBidPip" type="BigDecimal"/>
            <field name="feedComDukas" type="BigDecimal"/>
            <field name="feedComNonDukas" type="BigDecimal"/>
        </fields>
    </message>

    <message class="AccountInfoMessage">
        <fields>
            <field name="name" type="String"/>
            <field name="balance" type="BigDecimal"/>
            <field name="currency" type="String"/>
            <field name="equity" type="BigDecimal"/>
            <field name="baseEquity" type="BigDecimal"/>
            <field name="usableMargin" type="BigDecimal"/>
            <field name="leverage" type="Integer"/>
            <field name="global" type="boolean"/>
            <field name="feedCommision" type="BigDecimal"/>
            <field name="pl" type="BigDecimal"/>
            <field name="comm" type="BigDecimal"/>
            <field name="state" type="com.dukascopy.dds3.transport.msg.types.AccountState"/>
            <field name="onQuote" type="boolean"/>
            <field name="executor" type="boolean"/>
            <field name="noMc" type="boolean"/>
        </fields>
    </message>


    <message class="AccountInfoMessageInit" extends="AccountInfoMessage">
        <fields>
            <map name="clientSettings" keyClass="String" valueClass="String"/>
            <set name="positionIds" elementClass="String"/>
            <field name="comVol" type="BigDecimal"/>
            <field name="comPip" type="BigDecimal"/>
            <field name="comPipPerc" type="BigDecimal"/>
            <field name="miniFx" type="boolean"/>
            <field name="minAmount" type="BigDecimal"/>
            <field name="maxAmount" type="BigDecimal"/>
            <field name="mcEquityLimit" type="BigDecimal"/>
            <field name="mcLeverageUse" type="Integer"/>
            <field name="weekendLeverage" type="Integer"/>
            <field name="useExternal" type="boolean"/>
            <field name="maxGroups" type="Integer"/>
            <field name="maxOrders" type="Integer"/>
            <field name="mcMode" type="Integer"/>
            <field name="marginMode" type="Integer"/>
            <field name="executionMode" type="Integer"/>
            <list name="clients" elementClass="ClientInfoMessage"/>
            <set name="clientIds" elementClass="String"/>
            <field name="fxcmAccountReset" type="BigDecimal"/>
            <field name="executorType" type="Integer"/>
            <field name="wlPartnerId" type="Integer"/>
            <field name="feedCommissionMapId" type="Integer"/>
            <map name="feedCommissionMap" keyClass="String" valueClass="FeedCommission"/>
            <field name="wlTimes" type="String"/>
            <field name="orderGroupIdPrefix" type="String"/>
            <field name="contest" type="boolean"/>
            <field name="locked" type="boolean"/>
            <field name="mergeDenied" type="boolean"/>
            <field name="marginExt" type="String"/>
        </fields>
    </message>

    <message class="AccountInfoMessageLoad" extends="AccountInfoMessageInit">
        <fields>
            <field name="fundAccountId" type="String"/>
            <field name="fundRatio" type="Integer"/>
            <list name="executorBlackList" elementClass="String"/>
            <field name="sdExecutionDelay" type="Long"/>
            <field name="sdTrailingUsd" type="BigDecimal"/>
            <field name="gat" type="Integer"/>
            <field name="recordCount" type="Integer"/>
            <list name="primeBroker" elementClass="String"/>
            <map name="accountProperties" keyClass="String" valueClass="String"/>
            <field name="wlFund" type="String"/>
            <field name="wlFilter" type="boolean"/>
            <field name="allowSdex" type="Integer"/>
            <field name="fullReload" type="boolean"/>
            <field name="fundRatiosExt" type="String"/>
            <field name="roundScale" type="Integer"/>
            <field name="marginExt" type="String"/>
            <field name="ratioPrecision" type="BigDecimal"/>
            <field name="currencyExposureCalc" type="boolean"/>
            <field name="noRollover" type="boolean"/>
            <field name="managementType" type="Integer"/>
        </fields>
    </message>

    <message class="ExecutorAccountInfoMessage">
        <fields>
            <list name="groups" elementClass="com.dukascopy.dds3.transport.msg.ord.OrderGroupMessage"/>
            <field name="reloadType" type="String"/>
            <field name="account" type="AccountInfoMessageLoad"/>
        </fields>
    </message>
    <message class="ExecutorAccountsMessage">
        <fields>
            <list name="executors" elementClass="ExecutorAccountInfoMessage"/>
        </fields>
    </message>
    <message class="ManyUsersWarningMessage">
        <fields>
            <list name="userIdList" elementClass="String"/>
        </fields>
    </message>
    <message class="AccountInfoRequest">
        <constructor fields="action" />
        <fields>
            <map name="properties" keyClass="String" valueClass="String"/>
            <field name="action" type="String"/>
        </fields>
    </message>
    <message class="FundRatioChangeMessage">
        <fields>
            <map name="exposures" keyClass="String" valueClass="BigDecimal"/>
            <field name="oldRatio" type="Integer"/>
            <field name="newRatio" type="Integer"/>
            <field name="fundAccountId" type="String"/>
            <field name="reason" type="String"/>
            <field name="status" type="com.dukascopy.dds3.transport.msg.types.FundRatioChangeStatus"/>
        </fields>
    </message>

    <message class="FundRatioChangeGroupMessage">
        <fields>
            <list name="messages" elementClass="FundRatioChangeMessage" />
        </fields>
    </message>

</messages>

=== yukinago/famille-works/JForexStrategy/build/tmp/expandedArchives/msg-0.0.4.jar_26876983dr3metca3ffo8b6khc/feeder.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schema.xsd" package="com.dukascopy.dds3.transport.msg.feeder"
	autoExtends="com.dukascopy.dds4.transport.msg.system.ProtocolMessage">

	<message class="QuoteSubscribeRequestMessage">
		<fields>
			<field name="topOfBook" type="boolean" default="false">
				<comments>if true, then only best Ask and Bid will be received</comments>
			</field>
			<set name="instruments" elementClass="String"/>
			<field name="source" type="String">
				<comments>Optional datafeed source</comments>
			</field>
		</fields>
	</message>
	<message class="QuoteUnsubscribeRequestMessage">
		<fields>
			<set name="instruments" elementClass="String"/>
			<field name="source" type="String">
				<comments>Optional datafeed source</comments>
			</field>
		</fields>
	</message>


	<message class="InstrumentStatusUpdateMessage"
		implements="com.dukascopy.dds4.transport.msg.system.InstrumentableLowMessage">
		<fields>
			<field name="instrument" type="String" />
			<field name="state"
				type="com.dukascopy.dds3.transport.msg.types.TradabilityState" />
		</fields>
	</message>

	<message class="BestCurrencyMarketMessage"
		implements="com.dukascopy.dds4.transport.msg.system.InstrumentableLowMessage">
		<comments>Message for transfer bests of currencyMarket</comments>
		<fields>
			<field name="instrument" type="String" />
			<field name="bid"
				type="com.dukascopy.dds4.transport.msg.system.CurrencyOffer" />
			<field name="ask"
				type="com.dukascopy.dds4.transport.msg.system.CurrencyOffer" />
		</fields>
	</message>

	<message class="FeedHistoryRequestMessage">
		<fields>
			<field name="format" type="com.dukascopy.dds3.transport.msg.types.DataFormat" />
			<field name="marketDataType" type="String" />
			<field name="instrument" type="String" />
			<field name="side" type="com.dukascopy.dds3.transport.msg.types.OfferSide" />
			<field name="step" type="BigDecimal" />
			<field name="fromDate" type="Date" />
			<field name="toDate" type="Date" />
			<set name="sources" elementClass="String"/>
		</fields>
	</message>


</messages>
